apiVersion: v1
kind: Pod
metadata:
  name: dummy
spec:
  containers:
    - name: c1
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo hello-devops; sleep 4; done"]
      resources:
        requests:
          memory: 4Gi
        limits:
          memory: 6Gi
