apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: mylivenessprobe
spec:
  containers:
    - name: liveness
      image: ubuntu
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 1000

      # Define the health check for the container
      livenessProbe:
        exec:
          # Command Kubernetes runs periodically to check container health
          command:
            - ls
            - /tmp/healthy

        # Wait 30 seconds before running the first health check
        initialDelaySeconds: 30

        # Run the health check every 5 seconds
        periodSeconds: 5

        # Allow 30 seconds for the health check to complete
        timeoutSeconds: 30
