apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: nginx
          volumeMounts:
            - name: ebs-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: ebs-volume
          persistentVolumeClaim:
            claimName: myebs-pvc
