apiVersion: v1
kind: PersistentVolume
metadata:
  name: myebs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-069912088ba16d52
    fsType: ext4
