apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          # Change this to v2 to watch pods update one by one!
          image: sachinquamtumcloud/webpage:v1
          ports:
            - containerPort: 80
