apiVersion: v1
kind: Pod
metadata:
  name: db-pod-preferred
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: "role"
                operator: In
                values:
                  - database
  containers:
    - name: db-container
      image: mysql
