apiVersion: v1
kind: Pod
metadata:
  name: node-selector-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
  # This simple block forces the pod onto a node labeled with disk=ssd
  nodeSelector:
    disk: ssd
