apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: frontend
          topologyKey: "kubernetes.io/hostname"
  containers:
    - name: backend-container
      image: nginx
